"""empty message

Revision ID: 8e1cceb850fb
Revises: 
Create Date: 2023-05-15 22:49:45.448321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1cceb850fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infoProvider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender'), nullable=False),
    sa.Column('work_time', sa.Enum('Morning', 'Afternoon', 'Evening', name='worktime'), nullable=False),
    sa.Column('service', sa.Enum('Pet_Sitter', 'Pet_Walker', 'House_Sitter', 'Groomer', name='services'), nullable=False),
    sa.Column('allowed_pets', sa.Enum('Dogs', 'Cats', 'Birds', 'Horses', 'Reptiles', name='typepetsallowed'), nullable=False),
    sa.Column('number_admitted_pets', sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10'), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('accepted_payment_method', sa.Enum('Credit', 'Debit', 'Bank_Transfer', name='payment'), nullable=False),
    sa.Column('is_authenticated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accepted_payment_method'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('allowed_pets'),
    sa.UniqueConstraint('number_admitted_pets'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('is_authenticated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('infoUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender'), nullable=False),
    sa.Column('pets', sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10'), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('pet_size', sa.Enum('Small', 'Medium', 'Big', name='petsize'), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('payment_method', sa.Enum('Credit', 'Debit', 'Bank_Transfer', name='payment'), nullable=False),
    sa.Column('is_authenticated', sa.Boolean(), nullable=False),
    sa.Column('info_provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['info_provider_id'], ['infoProvider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('payment_method'),
    sa.UniqueConstraint('pets'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('is_authenticated', sa.Boolean(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruta', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('info_provider_id', sa.Integer(), nullable=True),
    sa.Column('info_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['info_provider_id'], ['infoProvider.id'], ),
    sa.ForeignKeyConstraint(['info_user_id'], ['infoUser.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('user')
    op.drop_table('infoUser')
    op.drop_table('token_blocked_list')
    op.drop_table('provider')
    op.drop_table('infoProvider')
    # ### end Alembic commands ###
